name: "Deploy"

on:
  pull_request:
    branches: 
      - stable

jobs:
  deploy:
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
    